/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.solace.aaron.restQ;

import com.solace.aaron.restQ.SolaceRestQueueConsumer;
import org.junit.Test;
import static org.junit.Assert.*;

public class BasicTest {
    @Test public void testAppHasAGreeting() {
        SolaceRestQueueConsumer classUnderTest = new SolaceRestQueueConsumer();
//        assertNotNull("app should have a greeting", classUnderTest.init("localhost","default","default"));
//        
//        UsefulUtils.
        
    }
}
